areas:
  corridor_start:
    pose: [1.2, 3.0, 0.0]
    type: start
  corridor_mid:
    pose: [6.0, 3.0, 0.0]
    type: corridor
  corridor_goal:
    pose: [10.8, 3.0, 0.0]
    type: goal
edges:
  corridor_start: [corridor_mid]
  corridor_mid: [corridor_start, corridor_goal]
  corridor_goal: [corridor_mid]
