areas:
  room_a:
    pose: [2.0, 3.0, 0.0]
    type: room
  doorway_center:
    pose: [6.0, 3.0, 0.0]
    type: doorway
  room_b:
    pose: [10.0, 3.0, 0.0]
    type: room
edges:
  room_a: [doorway_center]
  doorway_center: [room_a, room_b]
  room_b: [doorway_center]
